# Translating this into a human readable form, we are creating a workflow/action named Continuous Integration that runs on every pull request.
# This workflow consists of a single job called Build and Test that runs on ubuntu-latest.
# The job checks out the code submitted in the pull request, then installs all the dependencies, creates a build and runs all the tests once by passing the --watchAll=false option.
# If any of the steps fail, the whole workflow fails and reports back to the pull request.
# As a best practice we always enforce the checks to succeed before allowing code to be merged.

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ dev ]
    
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test --watchAll=false
